### ISSUE TITLE
Confirmed + Tentative + Rejected not always equal to number of features in final iteration?

### ISSUE THREAD

**Issue by JohnStott** [scikit-learn-contrib/boruta_py#70]
Hi,

it seems that throughout the `_print_results` method, the Confirmed + Tentative + Rejected is correct except for the final cycle in which it appears the "Tentative" value is incorrect.  Could this mean `self.support_weak_` is not always being updated correctly?

Here is an example of the output (see last cycle, where the values don't sum to the number of features?):

Iteration:      1 / 150
Confirmed:      0
Tentative:      47
Rejected:       0

....

Iteration:      148 / 150
Confirmed:      10
Tentative:      2
Rejected:       35

Iteration:      149 / 150
Confirmed:      10
Tentative:      2
Rejected:       35

BorutaPy finished running.

Iteration:      150 / 150
Confirmed:      10
Tentative:      1
Rejected:       35

**Comment by Naehil** [comment]
```self.support_weak_```, as well as ```self.support_``` are updated correctly, however internally the number of rejected features are miscounted in the last step.

**Comment by danielhomola** [comment]
this is fixed now. pull latest master and should be good.

**Comment by FeFortti** [comment]
This error is still happening. What happens is what @Naehil mentioned?
